/**
 * GitHub Copilot renderer. Exports a plain structurally-typed renderer consumed
 * by the distribution package via TypeScript structural typing; this package has
 * no internal dependencies (see ADR 0008 and the Gate 0 dependency direction).
 *
 * Copilot has no hook runtime (OPEN-DECISIONS OD-002): hook descriptors render
 * as documentation, not executable guards.
 */

export interface CanonicalAsset {
  name: string;
  content: string;
}

export interface CanonicalSkill extends CanonicalAsset {
  references: CanonicalAsset[];
}

export interface CanonicalAssets {
  version: string;
  skills: CanonicalSkill[];
  commands: CanonicalAsset[];
  hooks: CanonicalAsset[];
}

export interface RenderedFile {
  path: string;
  content: string;
}

function managedHeader(version: string, source: string): string {
  return [
    `<!-- MANAGED FILE - generated by product-definition (Product Definition as Code v${version})`,
    `     from ${source}. Do not edit by hand; run: product-definition integration update -->`,
  ].join('\n');
}

function withHeader(content: string, version: string, source: string): string {
  const header = managedHeader(version, source);
  const frontmatterEnd = /^---\n[\s\S]*?\n---\n/.exec(content);
  if (frontmatterEnd) {
    const index = frontmatterEnd[0].length;
    return `${content.slice(0, index)}\n${header}\n${content.slice(index)}`;
  }
  return `${header}\n\n${content}`;
}

interface HookDescriptor {
  name: string;
  description: string;
  triggers: { event: string; run: string[] }[];
  blocking: boolean;
  notes?: string;
}

function renderHookDoc(hook: HookDescriptor, version: string, source: string): string {
  const lines = [
    managedHeader(version, source),
    '',
    `# Hook: ${hook.name}`,
    '',
    hook.description,
    '',
    'GitHub Copilot has no hook runtime, so this guard is documentation: run the commands',
    'below yourself (or in CI) at the described moments.',
    '',
  ];
  for (const trigger of hook.triggers) {
    lines.push(`## ${trigger.event}`, '');
    for (const command of trigger.run) lines.push('```bash', command, '```', '');
  }
  if (hook.notes) lines.push(hook.notes, '');
  return lines.join('\n');
}

export const copilotRenderer = {
  provider: 'copilot',
  render(assets: CanonicalAssets): RenderedFile[] {
    const files: RenderedFile[] = [];

    for (const skill of assets.skills) {
      files.push({
        path: `.github/skills/${skill.name}.md`,
        content: withHeader(skill.content, assets.version, `skills/${skill.name}/SKILL.md`),
      });
      for (const reference of skill.references) {
        files.push({
          path: `.github/skills/${skill.name}-references/${reference.name}`,
          content: withHeader(
            reference.content,
            assets.version,
            `skills/${skill.name}/references/${reference.name}`,
          ),
        });
      }
    }

    for (const command of assets.commands) {
      files.push({
        path: `.github/prompts/product-${command.name}.prompt.md`,
        content: withHeader(command.content, assets.version, `commands/${command.name}.md`),
      });
    }

    for (const hook of assets.hooks) {
      const descriptor = JSON.parse(hook.content) as HookDescriptor;
      files.push({
        path: `.github/hooks/${descriptor.name}.md`,
        content: renderHookDoc(descriptor, assets.version, `hooks/${descriptor.name}.json`),
      });
    }

    return files.sort((a, b) => a.path.localeCompare(b.path));
  },
};
