/**
 * OpenCode renderer. Exports a plain structurally-typed renderer consumed by
 * the distribution package via TypeScript structural typing; this package has
 * no internal dependencies (see ADR 0008 and the Gate 0 dependency direction).
 *
 * Skills render to `.opencode/skills/<name>/SKILL.md` with `references/` inside
 * the skill directory. Commands render flat as
 * `.opencode/commands/product-<name>.md`: OpenCode has no subdirectory
 * namespacing, so the namespace lives in the filename as it does for Copilot.
 *
 * OpenCode also reads `.agents/skills` and `.claude/skills`, so a repository
 * that installs this provider alongside `codex` or `claude` gets the same
 * skills twice; the two differ on commands, which OpenCode reads only from
 * `.opencode/commands`.
 */

export interface CanonicalAsset {
  name: string;
  content: string;
}

export interface CanonicalSkill extends CanonicalAsset {
  references: CanonicalAsset[];
}

export interface CanonicalAssets {
  version: string;
  skills: CanonicalSkill[];
  commands: CanonicalAsset[];
  hooks: CanonicalAsset[];
}

export interface RenderedFile {
  path: string;
  content: string;
}

/**
 * Rendering choices supplied by the caller. Duplicated verbatim in the sibling integration
 * packages rather than shared: integrations declare no internal dependencies (ADR 0008) and are
 * consumed by structural typing.
 */
export interface RenderOptions {
  /** Emit `/ps:<name>` shorthand aliases alongside the canonical `/product:<name>` commands. */
  shorthandCommands?: boolean;
}

function managedHeader(version: string, source: string): string {
  return [
    `<!-- MANAGED FILE - generated by prodshape (Product Definition as Code v${version})`,
    `     from ${source}. Do not edit by hand; run: prodshape integration update -->`,
  ].join('\n');
}

function withHeader(content: string, version: string, source: string): string {
  const header = managedHeader(version, source);
  const frontmatterEnd = /^---\n[\s\S]*?\n---\n/.exec(content);
  if (frontmatterEnd) {
    const index = frontmatterEnd[0].length;
    return `${content.slice(0, index)}\n${header}\n${content.slice(index)}`;
  }
  return `${header}\n\n${content}`;
}

/** A YAML double-quoted scalar, whose escaping rules JSON's string form already satisfies. */
function yamlString(value: string): string {
  return JSON.stringify(value);
}

/** The first non-empty prose line after the H1, which is the command's one-line summary. */
function commandSummary(content: string): string | undefined {
  const lines = content.split('\n');
  const start = lines.findIndex((line) => line.startsWith('# '));
  if (start < 0) return undefined;
  return lines
    .slice(start + 1)
    .map((line) => line.trim())
    .find((line) => line !== '' && !line.startsWith('#') && !line.startsWith('<!--'));
}

/**
 * Give a command the `description` OpenCode's TUI lists it by. The canonical assets carry no
 * frontmatter, so it is synthesized; should one ever gain its own, the key is merged into that
 * block rather than emitted as a second one, which OpenCode would read as body text.
 */
function withCommandFrontmatter(content: string): string {
  const summary = commandSummary(content);
  if (!summary) return content;
  const existing = /^---\n([\s\S]*?)\n---\n/.exec(content);
  if (!existing) return `---\ndescription: ${yamlString(summary)}\n---\n\n${content}`;
  if (/^description:/m.test(existing[1]!)) return content;
  return `---\ndescription: ${yamlString(summary)}\n${content.slice(4)}`;
}

export const opencodeRenderer = {
  provider: 'opencode',
  render(assets: CanonicalAssets, options: RenderOptions = {}): RenderedFile[] {
    const files: RenderedFile[] = [];

    for (const skill of assets.skills) {
      files.push({
        path: `.opencode/skills/${skill.name}/SKILL.md`,
        content: withHeader(skill.content, assets.version, `skills/${skill.name}/SKILL.md`),
      });
      for (const reference of skill.references) {
        files.push({
          path: `.opencode/skills/${skill.name}/references/${reference.name}`,
          content: withHeader(
            reference.content,
            assets.version,
            `skills/${skill.name}/references/${reference.name}`,
          ),
        });
      }
    }

    // /product:<name> is canonical and always generated. /ps:<name> is an opt-in shorthand alias
    // with identical content: for a single-assistant repository it doubles the prompt namespace
    // without adding a capability.
    for (const command of assets.commands) {
      const rendered = withHeader(
        withCommandFrontmatter(command.content),
        assets.version,
        `commands/${command.name}.md`,
      );
      files.push({ path: `.opencode/commands/product-${command.name}.md`, content: rendered });
      if (options.shorthandCommands) {
        files.push({ path: `.opencode/commands/ps-${command.name}.md`, content: rendered });
      }
    }

    return files.sort((a, b) => a.path.localeCompare(b.path));
  },
};
