import {
  analyzeImpact,
  emitCitation,
  stableJson,
  validateBaseline,
  type LoadedArtifact,
} from '@prodshape/core';
import { CliError, exitCodes, resolveRepository, type CliIo } from '../context.js';

export interface ContextCliOptions {
  depth?: string;
  format?: 'markdown' | 'json';
  root?: string;
}

/** One artifact as reported in the projection, requested or related. */
interface ContextEntry {
  id: string;
  type?: string;
  title?: string;
  file: string;
  digest: string;
  citation: string;
}

function toEntry(artifact: LoadedArtifact): ContextEntry {
  return {
    id: artifact.id ?? '',
    ...(artifact.type !== undefined ? { type: artifact.type } : {}),
    ...(artifact.title !== undefined ? { title: artifact.title } : {}),
    file: artifact.file,
    digest: artifact.digest,
    citation: emitCitation({ id: artifact.id ?? '', digest: artifact.digest, form: 'inline' }),
  };
}

/**
 * `prodshape context` — render a bounded, cited context projection for delivery intake.
 *
 * The projection carries the requested artifacts' canonical text with ready-made inline
 * citations, plus the structurally related artifacts as a cited listing, so a delivery
 * specification (a Spec Kit specify run, an OpenSpec proposal, any consumer) starts
 * from cited product context instead of paraphrase. It is a derived, non-canonical projection:
 * regenerable at will, never a product artifact, never a "handoff" container. Deciding what to
 * build from it stays with the consumer; the projection only makes the grounding checkable, and
 * the emitted citations verify as `current` against the model they were generated from.
 *
 * Output is deterministic for a given model state: no timestamps, stable ordering.
 */
export async function runContext(
  io: CliIo,
  ids: string[],
  options: ContextCliOptions,
): Promise<number> {
  const format = options.format ?? 'markdown';
  if (format !== 'markdown' && format !== 'json') {
    throw new CliError(
      `Invalid --format '${String(options.format)}': expected markdown or json`,
      exitCodes.invalidInvocation,
    );
  }
  let depth = 1;
  if (options.depth !== undefined) {
    depth = Number(options.depth);
    if (!Number.isInteger(depth) || depth < 1) {
      throw new CliError(
        `Invalid --depth '${options.depth}': expected a positive integer`,
        exitCodes.invalidInvocation,
      );
    }
  }

  const repo = await resolveRepository(io, options.root);
  const { artifacts, graph } = await validateBaseline(repo);

  const requestedIds = [...new Set(ids)];
  for (const id of requestedIds) {
    if (!graph.nodeById.has(id)) {
      throw new CliError(`Unknown artifact ID '${id}'`, exitCodes.validationErrors);
    }
  }

  const byId = new Map(artifacts.filter((a) => a.id).map((a) => [a.id as string, a]));

  // Related artifacts: the structural neighborhood of every requested artifact, deduplicated,
  // excluding the requested set itself. Structural reachability only; no semantic claim.
  const relatedIds = new Set<string>();
  for (const id of requestedIds) {
    const report = analyzeImpact(graph, id, { direction: 'both', depth });
    for (const entry of [...report.direct, ...report.transitive]) {
      relatedIds.add(entry.id);
    }
  }
  for (const id of requestedIds) relatedIds.delete(id);

  const requested = requestedIds.map((id) => byId.get(id)).filter((a): a is LoadedArtifact => !!a);
  const related = [...relatedIds]
    .sort()
    .map((id) => byId.get(id))
    .filter((a): a is LoadedArtifact => !!a);

  if (format === 'json') {
    io.out(
      stableJson({
        schema: 'product-definition-as-code/context/v1alpha1',
        depth,
        requested: requested.map((a) => ({ ...toEntry(a), body: a.body })),
        related: related.map((a) => toEntry(a)),
      }).trimEnd(),
    );
    return exitCodes.success;
  }

  const lines: string[] = [];
  lines.push(
    '<!-- Generated by `prodshape context`. Derived, non-canonical projection of the product definition; regenerate at will. -->',
  );
  lines.push(`# Product context: ${requestedIds.join(', ')}`);
  lines.push('');
  lines.push(
    'This projection grounds delivery work (a Spec Kit specify run, an OpenSpec change, any consumer document) in cited canonical product text. Keep the citation lines next to the text they ground when deriving from it; verify them later with `prodshape citations verify`. The canonical definition stays in the product model; this file never replaces it.',
  );
  for (const artifact of requested) {
    const entry = toEntry(artifact);
    lines.push('');
    lines.push(
      `## ${entry.id}${entry.title ? ` ${entry.title}` : ''}${entry.type ? ` (${entry.type})` : ''}`,
    );
    lines.push('');
    lines.push(entry.citation);
    lines.push('');
    lines.push(artifact.body.trim());
  }
  if (related.length > 0) {
    lines.push('');
    lines.push(`## Related artifacts (structural neighborhood, depth ${depth})`);
    lines.push('');
    lines.push(
      'Cite any of these the derived work also depends on; the citation record is ready on each line.',
    );
    for (const artifact of related) {
      const entry = toEntry(artifact);
      lines.push(
        `- ${entry.id}${entry.title ? ` ${entry.title}` : ''}${entry.type ? ` (${entry.type})` : ''}: ${entry.citation}`,
      );
    }
  }
  io.out(lines.join('\n'));
  return exitCodes.success;
}
