/**
 * Claude Code renderer. Exports a plain structurally-typed renderer consumed by
 * the distribution package via TypeScript structural typing; this package has
 * no internal dependencies (see ADR 0008 and the Gate 0 dependency direction).
 */

export interface CanonicalAsset {
  name: string;
  content: string;
}

export interface CanonicalSkill extends CanonicalAsset {
  references: CanonicalAsset[];
}

export interface CanonicalAssets {
  /** Framework version stamped into managed headers. */
  version: string;
  skills: CanonicalSkill[];
  commands: CanonicalAsset[];
  hooks: CanonicalAsset[];
}

export interface RenderedFile {
  /** Consumer-repository-relative path, POSIX separators. */
  path: string;
  content: string;
}

/**
 * Rendering choices supplied by the caller. Duplicated verbatim in the sibling integration
 * package rather than shared: integrations declare no internal dependencies (ADR 0008) and are
 * consumed by structural typing.
 */
export interface RenderOptions {
  /** Emit `/ps:<name>` shorthand aliases alongside the canonical `/product:<name>` commands. */
  shorthandCommands?: boolean;
}

function managedHeader(version: string, source: string): string {
  return [
    `<!-- MANAGED FILE - generated by prodshape (Product Definition as Code v${version})`,
    `     from ${source}. Do not edit by hand; run: prodshape integration update -->`,
  ].join('\n');
}

/** Insert the managed header after YAML frontmatter (which must stay first). */
function withHeader(content: string, version: string, source: string): string {
  const header = managedHeader(version, source);
  const frontmatterEnd = /^---\n[\s\S]*?\n---\n/.exec(content);
  if (frontmatterEnd) {
    const index = frontmatterEnd[0].length;
    return `${content.slice(0, index)}\n${header}\n${content.slice(index)}`;
  }
  return `${header}\n\n${content}`;
}

export const claudeRenderer = {
  provider: 'claude',
  render(assets: CanonicalAssets, options: RenderOptions = {}): RenderedFile[] {
    const files: RenderedFile[] = [];

    for (const skill of assets.skills) {
      files.push({
        path: `.claude/skills/${skill.name}/SKILL.md`,
        content: withHeader(skill.content, assets.version, `skills/${skill.name}/SKILL.md`),
      });
      for (const reference of skill.references) {
        files.push({
          path: `.claude/skills/${skill.name}/references/${reference.name}`,
          content: withHeader(
            reference.content,
            assets.version,
            `skills/${skill.name}/references/${reference.name}`,
          ),
        });
      }
    }

    // Subdirectory namespacing exposes these as /product:<name>, which is canonical and always
    // generated. /ps:<name> is an opt-in shorthand alias resolving to the same command: for a
    // single-assistant repository it doubles the command namespace without adding a capability.
    for (const command of assets.commands) {
      const rendered = withHeader(command.content, assets.version, `commands/${command.name}.md`);
      files.push({ path: `.claude/commands/product/${command.name}.md`, content: rendered });
      if (options.shorthandCommands) {
        files.push({ path: `.claude/commands/ps/${command.name}.md`, content: rendered });
      }
    }

    // Hooks render as a ready-to-merge fragment: user settings are never edited directly.
    const descriptors = assets.hooks.map((hook) => JSON.parse(hook.content) as unknown);
    files.push({
      path: '.claude/hooks/product-definition.json',
      content: `${JSON.stringify(
        {
          managed: {
            by: 'prodshape',
            version: assets.version,
            source: 'hooks/',
            note: 'Generated fragment. Wire these deterministic commands into your hook configuration; do not edit by hand - run: prodshape integration update',
          },
          hooks: descriptors,
        },
        null,
        2,
      )}\n`,
    });

    return files.sort((a, b) => a.path.localeCompare(b.path));
  },
};
