/**
 * Codex-compatible renderer. Exports a plain structurally-typed renderer consumed
 * by the distribution package via TypeScript structural typing; this package has
 * no internal dependencies (see ADR 0008 and the Gate 0 dependency direction).
 *
 * Targets the Agent Skills open standard (agentskills.io) using the `.agents/`
 * discovery path supported by VS Code, OpenAI Codex, and other Agent Skills
 * compatible tools. Skills render as directory-based portable skills:
 * `.agents/skills/<name>/SKILL.md` with `references/` inside the skill directory.
 */

export interface CanonicalAsset {
  name: string;
  content: string;
}

export interface CanonicalSkill extends CanonicalAsset {
  references: CanonicalAsset[];
}

export interface CanonicalAssets {
  version: string;
  skills: CanonicalSkill[];
  commands: CanonicalAsset[];
  hooks: CanonicalAsset[];
}

export interface RenderedFile {
  path: string;
  content: string;
}

/**
 * Rendering choices supplied by the caller. Duplicated verbatim in the sibling integration
 * packages rather than shared: integrations declare no internal dependencies (ADR 0008) and are
 * consumed by structural typing.
 */
export interface RenderOptions {
  /** Emit `/ps:<name>` shorthand aliases alongside the canonical `/product:<name>` commands. */
  shorthandCommands?: boolean;
}

function managedHeader(version: string, source: string): string {
  return [
    `<!-- MANAGED FILE - generated by prodshape (Product Definition as Code v${version})`,
    `     from ${source}. Do not edit by hand; run: prodshape integration update -->`,
  ].join('\n');
}

function withHeader(content: string, version: string, source: string): string {
  const header = managedHeader(version, source);
  const frontmatterEnd = /^---\n[\s\S]*?\n---\n/.exec(content);
  if (frontmatterEnd) {
    const index = frontmatterEnd[0].length;
    return `${content.slice(0, index)}\n${header}\n${content.slice(index)}`;
  }
  return `${header}\n\n${content}`;
}

export const codexRenderer = {
  provider: 'codex',
  render(assets: CanonicalAssets, options: RenderOptions = {}): RenderedFile[] {
    const files: RenderedFile[] = [];

    // Agent Skills standard: .agents/skills/<name>/SKILL.md with references/ inside.
    for (const skill of assets.skills) {
      files.push({
        path: `.agents/skills/${skill.name}/SKILL.md`,
        content: withHeader(skill.content, assets.version, `skills/${skill.name}/SKILL.md`),
      });
      for (const reference of skill.references) {
        files.push({
          path: `.agents/skills/${skill.name}/references/${reference.name}`,
          content: withHeader(
            reference.content,
            assets.version,
            `skills/${skill.name}/references/${reference.name}`,
          ),
        });
      }
    }

    // Commands render as prompt files under .agents/commands/ using subdirectory namespacing
    // (supported by Claude Code and other Agent Skills compatible tools).
    for (const command of assets.commands) {
      const rendered = withHeader(command.content, assets.version, `commands/${command.name}.md`);
      files.push({ path: `.agents/commands/product/${command.name}.md`, content: rendered });
      if (options.shorthandCommands) {
        files.push({ path: `.agents/commands/ps/${command.name}.md`, content: rendered });
      }
    }

    return files.sort((a, b) => a.path.localeCompare(b.path));
  },
};
