/**
 * Extract the normative diagnostic registry from the spec repository's `spec/validation.md`,
 * pinned to the commit SHA recorded in `docs/specification/.source.json`, and vendor it as
 * `docs/specification/.spec-registry.json`.
 *
 * The spec repository (product-definition-as-code/spec) owns the registry: which diagnostic codes
 * exist and what severity each carries. This repository documents the same codes in
 * `docs/specification/validation.md`, plus the implementation-specific ones it issues on top. The
 * conformance test compares the two — but it can only detect drift against a recorded revision, so
 * the extract is vendored rather than fetched at test time: `pnpm test` stays offline and
 * deterministic, and a spec revision bump becomes an explicit, reviewable diff.
 *
 * Run with: pnpm registry:sync
 */
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = fileURLToPath(new URL('..', import.meta.url));
const specDir = join(repoRoot, 'docs', 'specification');
const sourcePath = join(specDir, '.source.json');
const registryPath = join(specDir, '.spec-registry.json');

interface RegistrySource {
  repo: string;
  path: string;
  ref: string;
}

const source = JSON.parse(await readFile(sourcePath, 'utf8')) as RegistrySource;

const url = `https://raw.githubusercontent.com/${source.repo}/${source.ref}/${source.path}`;
const response = await fetch(url);
if (!response.ok) {
  throw new Error(
    `Failed to fetch ${source.path} from ${source.repo}@${source.ref.slice(0, 8)}: ${response.status} ${response.statusText}`,
  );
}
const document = await response.text();

/** The rows of one `## <heading>` section's table, as `PRODUCTNNN` codes. */
function codesUnder(heading: string): string[] {
  const start = document.indexOf(`## ${heading}`);
  if (start === -1) throw new Error(`The pinned spec has no '## ${heading}' section`);
  const rest = document.slice(start + heading.length);
  const end = rest.indexOf('\n## ');
  const section = end === -1 ? rest : rest.slice(0, end);
  // Only table rows define a code; prose below a table references codes without defining them.
  const codes = new Set<string>();
  for (const line of section.split('\n')) {
    const row = /^\|\s*`(PRODUCT\d{3})`\s*\|/.exec(line);
    if (row?.[1]) codes.add(row[1]);
  }
  if (codes.size === 0) throw new Error(`The pinned spec's '## ${heading}' table lists no codes`);
  return [...codes].sort();
}

const severityByCode: Record<string, 'error' | 'warning'> = {};
for (const code of codesUnder('Error codes')) severityByCode[code] = 'error';
for (const code of codesUnder('Warning codes')) {
  if (severityByCode[code] !== undefined) {
    throw new Error(`The pinned spec lists ${code} under both Error codes and Warning codes`);
  }
  severityByCode[code] = 'warning';
}

const registry = {
  note: 'Generated by `pnpm registry:sync` from the pinned spec revision in .source.json. Do not edit by hand.',
  source,
  codes: Object.fromEntries(Object.entries(severityByCode).sort(([a], [b]) => (a < b ? -1 : 1))),
};

await writeFile(registryPath, `${JSON.stringify(registry, null, 2)}\n`, 'utf8');

const errors = Object.values(severityByCode).filter((s) => s === 'error').length;
const warnings = Object.values(severityByCode).length - errors;
console.log(
  `Extracted ${errors} error code(s) and ${warnings} warning code(s) from ${source.repo}@${source.ref.slice(0, 8)} into docs/specification/.spec-registry.json`,
);
